// Auto-generated by swift-openapi-bootstrapper

import Testing
import SpeechallAPI
import SpeechallAPITypes
import OpenAPIAsyncHTTPClient
import OpenAPIRuntime
import UsefulThings
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif

struct SpeechallAPITests {
     let client = {
         let envFileUrl = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent().appendingPathComponent(".env")
         guard let apiKey = UsefulThings.getEnvironmentVariable("API_KEY", from: envFileUrl) else {
             preconditionFailure()
         }
         return SpeechallAPI.Client(
            serverURL: URL(string: "https://api.speechall.com/v1")!,
            transport: AsyncHTTPClientTransport(),
            middlewares: [AuthenticationMiddleware(apiKey: apiKey)]
         )
     }()

    @Test func listSpeechToTextModelsMatchesGeneratedEnum() async throws {
        let response = try await client.listSpeechToTextModels()

        let models: [Components.Schemas.SpeechToTextModel]
        switch response {
        case .ok(let ok):
            models = try ok.body.json
        case .badRequest(let badRequest):
            Issue.record("Bad request: \(try badRequest.body.json.message)")
            return
        case .unauthorized(let unauthorized):
            Issue.record("Unauthorized: \(try unauthorized.body.json.message)")
            return
        case .code402(let paymentRequired):
            Issue.record("Payment required: \(try paymentRequired.body.json.message)")
            return
        case .notFound(let notFound):
            Issue.record("Not found: \(try notFound.body.json.message)")
            return
        case .tooManyRequests(let tooManyRequests):
            Issue.record("Too many requests: \(try tooManyRequests.body.json.message)")
            return
        case .internalServerError(let internalServerError):
            Issue.record("Internal server error: \(try internalServerError.body.json.message)")
            return
        case .serviceUnavailable(let serviceUnavailable):
            Issue.record("Service unavailable: \(try serviceUnavailable.body.json.message)")
            return
        case .gatewayTimeout(let gatewayTimeout):
            Issue.record("Gateway timeout: \(try gatewayTimeout.body.json.message)")
            return
        case .undocumented(let statusCode, _):
            Issue.record("Undocumented response with status code \(String(statusCode))")
            return
        }

        let apiIDs = models.map(\.id.rawValue).sorted()
        let generatedIDs = Components.Schemas.TranscriptionModelIdentifier.allCases.map(\.rawValue).sorted()

        print("Speech-to-text models returned by API (\(apiIDs.count)):")
        for modelID in apiIDs {
            print("- \(modelID)")
        }

        #expect(
            apiIDs.allSatisfy { $0.contains(".") },
            "Every model ID should be in `provider.model` format. IDs: \(apiIDs.joined(separator: ", "))"
        )

        let apiIDSet = Set(apiIDs)
        let generatedIDSet = Set(generatedIDs)
        let duplicateAPIIDs = Dictionary(grouping: apiIDs, by: { $0 })
            .filter { $0.value.count > 1 }
            .keys
            .sorted()
        let missingFromAPI = generatedIDSet.subtracting(apiIDSet).sorted()
        let missingFromGeneratedEnum = apiIDSet.subtracting(generatedIDSet).sorted()

        #expect(
            duplicateAPIIDs.isEmpty,
            "API returned duplicate model IDs: \(duplicateAPIIDs.joined(separator: ", "))"
        )
        #expect(
            missingFromAPI.isEmpty,
            "Generated enum contains IDs missing from API: \(missingFromAPI.joined(separator: ", "))"
        )
        #expect(
            missingFromGeneratedEnum.isEmpty,
            "API returned IDs missing from generated enum: \(missingFromGeneratedEnum.joined(separator: ", "))"
        )
    }

    @Test func example() async throws {
        let audioData = try Data(contentsOf: URL(filePath: "/Users/atacan/Developer/Repositories/Speechall-SDK/speechall-typescript-sdk/examples/sample-audio.wav"))
        let response = try await client.transcribe(
            query: .init(model: .cloudflare_period_whisper),
            body: .audio__ast_(
                HTTPBody(
                    audioData
                )
            )
         )
        switch response {
        case .ok(let dualFormatTranscriptionResponse):
            switch dualFormatTranscriptionResponse.body {
            case .json(let transcriptionResponse):
                switch transcriptionResponse {
                case .TranscriptionDetailed(let transcriptionDetailed):
                    print(transcriptionDetailed.text)
                case .TranscriptionOnlyText(let transcriptionOnlyText):
                    print(transcriptionOnlyText.text)
                }
            case .plainText(let httpBody):
                let responseString = String(buffer: try await httpBody.collect(upTo: 1024 * 1024, using: .init()))
            }
        case .badRequest(let badRequest):
            print(try badRequest.body.json.message)
        case .unauthorized(let unauthorized):
            print(try unauthorized.body.json.message)
        case .code402(let paymentRequired):
            print(try paymentRequired.body.json.message)
        case .notFound(let notFound):
            print(try notFound.body.json.message)
        case .tooManyRequests(let tooManyRequests):
            print(try tooManyRequests.body.json.message)
        case .internalServerError(let internalServerError):
            print(try internalServerError.body.json.message)
        case .serviceUnavailable(let serviceUnavailable):
            print(try serviceUnavailable.body.json.message)
        case .gatewayTimeout(let gatewayTimeout):
            print(try gatewayTimeout.body.json.message)
        case .undocumented(let statusCode, let undocumentedPayload):
            // undocumentedPayload.body is HTTPBody
            if let buffer = try await undocumentedPayload.body?.collect(upTo: 1024 * 1024, using: .init()){
                let payloadString = String(buffer: buffer)
                print(payloadString)
            }
            
        }
    }

    
}
