// Auto-generated by swift-openapi-bootstrapper

import Testing
import SpeechallAPI
import SpeechallAPITypes
import OpenAPIAsyncHTTPClient
import OpenAPIRuntime
import UsefulThings
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif

func shouldSkipTransientLiveAPIError(_ error: any Error, operation: String) -> Bool {
    let description = String(describing: error)
    let isServerError = description.contains("internalServerError")
        || description.contains("response: serviceUnavailable")
        || description.contains("response: gatewayTimeout")
        || description.contains("Unexpected response body")
    let isPlainTextErrorBody = description.contains("plainText")

    guard isServerError && isPlainTextErrorBody else { return false }
    print("Skipping live \(operation) check because the API returned a transient non-JSON error body: \(error)")
    return true
}

struct SpeechallAPITests {
     let client = {
         let envFileUrl = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent().appendingPathComponent(".env")
         guard let apiKey = UsefulThings.getEnvironmentVariable("API_KEY", from: envFileUrl) else {
             preconditionFailure()
         }
         return SpeechallAPI.Client(
            serverURL: URL(string: "https://api.speechall.com/v1")!,
            transport: AsyncHTTPClientTransport(),
            middlewares: [AuthenticationMiddleware(apiKey: apiKey)]
         )
    }()

    @Test func listSpeechToTextModelsUseGeneratedEnumIdentifiers() async throws {
        let response: Operations.listSpeechToTextModels.Output
        do {
            response = try await client.listSpeechToTextModels()
        } catch let error as ClientError {
            if let statusCode = error.response?.status.code,
               statusCode == 429 || (500...599).contains(statusCode) {
                print("Skipping live model-list enum check because the API returned HTTP \(statusCode): \(error)")
                return
            }
            throw error
        } catch {
            if shouldSkipTransientLiveAPIError(error, operation: "model-list enum") {
                return
            }
            throw error
        }

        let models: [Components.Schemas.SpeechToTextModel]
        switch response {
        case .ok(let ok):
            models = try ok.body.json
        case .badRequest(let badRequest):
            Issue.record("Bad request: \(try badRequest.body.json.message)")
            return
        case .unauthorized(let unauthorized):
            Issue.record("Unauthorized: \(try unauthorized.body.json.message)")
            return
        case .code402(let paymentRequired):
            Issue.record("Payment required: \(try paymentRequired.body.json.message)")
            return
        case .notFound(let notFound):
            Issue.record("Not found: \(try notFound.body.json.message)")
            return
        case .tooManyRequests(let tooManyRequests):
            print("Skipping live model-list enum check because the API returned 429: \(tooManyRequests.body)")
            return
        case .internalServerError(let internalServerError):
            print("Skipping live model-list enum check because the API returned 500: \(internalServerError.body)")
            return
        case .serviceUnavailable(let serviceUnavailable):
            print("Skipping live model-list enum check because the API returned 503: \(serviceUnavailable.body)")
            return
        case .gatewayTimeout(let gatewayTimeout):
            print("Skipping live model-list enum check because the API returned 504: \(gatewayTimeout.body)")
            return
        case .undocumented(let statusCode, _):
            Issue.record("Undocumented response with status code \(String(statusCode))")
            return
        }

        let apiIDs = models.map(\.id.rawValue).sorted()
        let generatedIDs = Components.Schemas.TranscriptionModelIdentifier.allCases.map(\.rawValue).sorted()

        print("Speech-to-text models returned by API (\(apiIDs.count)):")
        for modelID in apiIDs {
            print("- \(modelID)")
        }

        #expect(
            apiIDs.allSatisfy { $0.contains(".") },
            "Every model ID should be in `provider.model` format. IDs: \(apiIDs.joined(separator: ", "))"
        )

        let apiIDSet = Set(apiIDs)
        let generatedIDSet = Set(generatedIDs)
        let duplicateAPIIDs = Dictionary(grouping: apiIDs, by: { $0 })
            .filter { $0.value.count > 1 }
            .keys
            .sorted()
        let missingFromGeneratedEnum = apiIDSet.subtracting(generatedIDSet).sorted()
        let inactiveGeneratedIDs = generatedIDSet.subtracting(apiIDSet).sorted()

        #expect(
            duplicateAPIIDs.isEmpty,
            "API returned duplicate model IDs: \(duplicateAPIIDs.joined(separator: ", "))"
        )
        #expect(
            missingFromGeneratedEnum.isEmpty,
            "API returned IDs missing from generated enum: \(missingFromGeneratedEnum.joined(separator: ", "))"
        )

        if !inactiveGeneratedIDs.isEmpty {
            print("Generated enum IDs not returned by the live API (\(inactiveGeneratedIDs.count)):")
            for modelID in inactiveGeneratedIDs {
                print("- \(modelID)")
            }
        }
    }

    @Test func example() async throws {
        let audioData = try Data(contentsOf: URL(filePath: "/Users/atacan/Developer/Repositories/Speechall-SDK/speechall-typescript-sdk/examples/sample-audio.wav"))
        let response: Operations.transcribe.Output
        do {
            response = try await client.transcribe(
                query: .init(model: .cloudflare_period_whisper),
                body: .audio__ast_(
                    HTTPBody(
                        audioData
                    )
                )
            )
        } catch {
            if shouldSkipTransientLiveAPIError(error, operation: "raw transcription") {
                return
            }
            throw error
        }

        switch response {
        case .ok(let dualFormatTranscriptionResponse):
            switch dualFormatTranscriptionResponse.body {
            case .json(let transcriptionResponse):
                switch transcriptionResponse {
                case .TranscriptionDetailed(let transcriptionDetailed):
                    print(transcriptionDetailed.text)
                case .TranscriptionOnlyText(let transcriptionOnlyText):
                    print(transcriptionOnlyText.text)
                }
            case .plainText(let httpBody):
                print(String(buffer: try await httpBody.collect(upTo: 1024 * 1024, using: .init())))
            }
        case .badRequest(let badRequest):
            print(try badRequest.body.json.message)
        case .unauthorized(let unauthorized):
            print(try unauthorized.body.json.message)
        case .code402(let paymentRequired):
            print(try paymentRequired.body.json.message)
        case .notFound(let notFound):
            print(try notFound.body.json.message)
        case .tooManyRequests(let tooManyRequests):
            print("Skipping live raw transcription check because the API returned 429: \(tooManyRequests.body)")
        case .internalServerError(let internalServerError):
            print("Skipping live raw transcription check because the API returned 500: \(internalServerError.body)")
        case .serviceUnavailable(let serviceUnavailable):
            print("Skipping live raw transcription check because the API returned 503: \(serviceUnavailable.body)")
        case .gatewayTimeout(let gatewayTimeout):
            print("Skipping live raw transcription check because the API returned 504: \(gatewayTimeout.body)")
        case .undocumented(_, let undocumentedPayload):
            // undocumentedPayload.body is HTTPBody
            if let buffer = try await undocumentedPayload.body?.collect(upTo: 1024 * 1024, using: .init()){
                let payloadString = String(buffer: buffer)
                print(payloadString)
            }
            
        }
    }

    
}
